/*DELETE COLUMNS (GOAL, SHOTON, SHOTOFF, FOULCOMMIT, CARD, "CROSS",	CORNER, POSSESSION) FROM MATCH TABLE*/
ALTER TABLE MATCH
DROP COLUMN GOAL, SHOTON, SHOTOFF, FOULCOMMIT, CARD, "CROSS",	CORNER, POSSESSION;

/*ADD COUNTRY_ID COLUMN IN TEAM TABLE AND SET FOREIGN KEY OF COUNTRY ID FROM COUNTRY TABLE TO TEAM TABLE*/
ALTER TABLE TEAM
ADD COUNTRY_ID INT4, 
ADD CONSTRAINT FK_COUNTRY_TEAM FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRY (ID)
ON DELETE CASCADE ON UPDATE CASCADE;

/*ENGLAND*/
UPDATE TEAM SET COUNTRY_ID = 1729
WHERE TEAM_API_ID IN (SELECT HOME_TEAM_API_ID FROM "MATCH" WHERE LEAGUE_ID  = 1729);

/*FRANCE*/
UPDATE TEAM SET COUNTRY_ID = 4769
WHERE TEAM_API_ID IN (SELECT HOME_TEAM_API_ID FROM "MATCH" WHERE LEAGUE_ID  = 4769);

/*GERMANY*/
UPDATE TEAM SET COUNTRY_ID = 7809
WHERE TEAM_API_ID IN (SELECT HOME_TEAM_API_ID FROM "MATCH" WHERE LEAGUE_ID  = 7809);

/*ITALY*/
UPDATE TEAM SET COUNTRY_ID = 10257
WHERE TEAM_API_ID IN (SELECT HOME_TEAM_API_ID FROM "MATCH" WHERE LEAGUE_ID  = 10257);

/*SPAIN*/
UPDATE TEAM SET COUNTRY_ID = 21518
WHERE TEAM_API_ID IN (SELECT HOME_TEAM_API_ID FROM "MATCH" WHERE LEAGUE_ID  = 21518);

SELECT * FROM "MATCH" M;

/*DELETE TEAMS THAT ARE NOT PART OF TOP 5 LEAGUES IN TEAM TABLE*/
DELETE FROM TEAM
WHERE COUNTRY_ID IS NULL;

/*TOTAL TEAM PARTICIPANTS IN EACH LEAGUE IN A SEASON*/
WITH TEAMS_BY_COUNTRY
AS (
SELECT M.SEASON,  C.NAME AS COUNTRY, COUNT(DISTINCT M.HOME_TEAM_API_ID) AS TOTAL_TEAMS 
FROM TEAM T 
JOIN COUNTRY C 
ON T.COUNTRY_ID = C.ID
JOIN "MATCH" M 
ON M.COUNTRY_ID = C.ID
GROUP BY M.SEASON, C.NAME
ORDER BY M.SEASON)

SELECT COUNTRY, AVG(TOTAL_TEAMS) AS TOTAL_PARTICIPANTS
FROM TEAMS_BY_COUNTRY
GROUP BY COUNTRY;

/*DELETE TEAMS THAT ARE NOT FROM TOP 5 LEAGUES IN MATCH TABLE*/
DELETE FROM "MATCH"  
WHERE COUNTRY_ID IN (
SELECT C.ID 
FROM COUNTRY C
WHERE C.NAME NOT IN ('SPAIN', 'FRANCE', 'ENGLAND', 'GERMANY', 'ITALY'));

/*FIND LIST OF TEAMS THAT NEVER BEEN RELEGATED BY COUNTRY FOR ENTIRE SEASON*/
CREATE VIEW NOT_RELEGATED_TEAMS AS
WITH CTE
AS (
SELECT T.TEAM_API_ID, SEASON, C.NAME AS COUNTRY, T.TEAM_LONG_NAME  AS TEAM
FROM "MATCH" M  
FULL JOIN TEAM T
ON M.HOME_TEAM_API_ID = T.TEAM_API_ID
JOIN COUNTRY C 
ON T.COUNTRY_ID = C.ID 
GROUP BY SEASON, T.TEAM_API_ID, C.NAME, T.TEAM_LONG_NAME
)
SELECT TEAM
FROM CTE
GROUP BY TEAM 
HAVING COUNT(*) = 8
ORDER BY TEAM;

SELECT *
FROM NOT_RELEGATED_TEAMS; 

/*FIND TOTAL TEAMS THAT NEVER BEEN RELEGATED BY COUNTRY*/
SELECT C.NAME AS COUNTRY, COUNT(*) AS TOTAL_TEAMS 
FROM TEAM T 
JOIN COUNTRY C 
ON T.COUNTRY_ID = C.ID
WHERE T.TEAM_LONG_NAME IN (SELECT * FROM NOT_RELEGATED_TEAMS)
GROUP BY C.NAME
ORDER BY COUNT(*) DESC;

/*TOTAL TEAM PARTICIPANTS IN EACH LEAGUE IN A SEASON*/
WITH CTE
AS (
SELECT M.SEASON,  C.NAME AS COUNTRY, COUNT(DISTINCT M.HOME_TEAM_API_ID) AS TOTAL_TEAMS 
FROM TEAM T 
JOIN COUNTRY C 
ON T.COUNTRY_ID = C.ID
JOIN "MATCH" M 
ON M.COUNTRY_ID = C.ID
GROUP BY M.SEASON, C.NAME
ORDER BY M.SEASON)

SELECT COUNTRY, AVG(TOTAL_TEAMS) AS TOTAL_PARTICIPANTS
FROM CTE 
GROUP BY COUNTRY;

/*TOTAL TEAM GOALS EACH SEASON*/
CREATE VIEW TOTAL_TEAM_GOALS
AS 
SELECT T1.SEASON,
T1.TEAM,
T1.COUNTRY,
T1.LEAGUE,
T1.TOTAL_HOME_GOAL,
T2.TOTAL_AWAY_GOAL,
T1.TOTAL_HOME_GOAL+T2.TOTAL_AWAY_GOAL AS TOTAL_GOALS
FROM
	(SELECT SEASON,
	TEAM_LONG_NAME AS TEAM,
	C.NAME AS COUNTRY,
	L.NAME AS LEAGUE,
	SUM(HOME_TEAM_GOAL) AS TOTAL_HOME_GOAL
	FROM TEAM T
	JOIN "MATCH" M
	ON T.TEAM_API_ID = M.HOME_TEAM_API_ID
	JOIN COUNTRY C
	ON M.COUNTRY_ID = C.ID
	JOIN LEAGUE L
	ON M.LEAGUE_ID = L.ID
	GROUP BY SEASON, TEAM_LONG_NAME, C.NAME, L.NAME
) T1
JOIN
	(SELECT SEASON,
	TEAM_LONG_NAME AS TEAM,
	C.NAME AS COUNTRY,
	L.NAME AS LEAGUE,
	SUM(AWAY_TEAM_GOAL) AS TOTAL_AWAY_GOAL
	FROM TEAM T
	JOIN "MATCH" M
	ON T.TEAM_API_ID = M.AWAY_TEAM_API_ID
	JOIN COUNTRY C
	ON M.COUNTRY_ID = C.ID
	JOIN LEAGUE L
	ON M.LEAGUE_ID = L.ID
	GROUP BY SEASON, TEAM_LONG_NAME, C.NAME, L.NAME
) T2
ON T1.SEASON = T2.SEASON
AND T1.TEAM = T2.TEAM
AND T1.COUNTRY = T2.COUNTRY
ORDER BY TOTAL_GOALS DESC;

SELECT * FROM TOTAL_TEAM_GOALS;

/*TOTAL TEAM GOALS CONCEDED EACH SEASON*/
CREATE VIEW TOTAL_TEAM_CONCEDED
AS
SELECT
T1.SEASON,
T1.TEAM,
T1.COUNTRY,
T1.LEAGUE,
T1.TOTAL_HOME_CONCEDED,
T2.TOTAL_AWAY_CONCEDED,
SUM(T1.TOTAL_HOME_CONCEDED+T2.TOTAL_AWAY_CONCEDED) AS TOTAL_GOALS_CONCEDED
FROM
	(SELECT SEASON,
	T.TEAM_API_ID, 
	T.TEAM_LONG_NAME AS TEAM,
	C.NAME AS COUNTRY,
	L.NAME AS LEAGUE,
	SUM(AWAY_TEAM_GOAL) AS TOTAL_HOME_CONCEDED
	FROM "MATCH" M 
	JOIN TEAM T 
	ON M.HOME_TEAM_API_ID = T.TEAM_API_ID 
	JOIN COUNTRY C 
	ON M.COUNTRY_ID = C.ID 
	JOIN LEAGUE L
	ON M.LEAGUE_ID = L.ID
	GROUP BY SEASON, T.TEAM_LONG_NAME, C.NAME, L.NAME, T.TEAM_API_ID
	) T1
JOIN 
	(SELECT SEASON,
	T.TEAM_API_ID, 
	T.TEAM_LONG_NAME AS TEAM,
	C.NAME AS COUNTRY,
	L.NAME AS LEAGUE,
	SUM(HOME_TEAM_GOAL) AS TOTAL_AWAY_CONCEDED
	FROM "MATCH" M 
	JOIN TEAM T 
	ON M.AWAY_TEAM_API_ID = T.TEAM_API_ID 
	JOIN COUNTRY C 
	ON M.COUNTRY_ID = C.ID 
	JOIN LEAGUE L
	ON M.LEAGUE_ID = L.ID
	GROUP BY SEASON, T.TEAM_LONG_NAME, C.NAME, L.NAME, T.TEAM_API_ID
	) T2
ON 	T1.SEASON = T2.SEASON
AND T1.TEAM = T2.TEAM
AND T1.COUNTRY = T2.COUNTRY
GROUP BY T1.SEASON, T1.TEAM, T1.COUNTRY, T1.LEAGUE, T1.TOTAL_HOME_CONCEDED, T2.TOTAL_AWAY_CONCEDED
ORDER BY TOTAL_GOALS_CONCEDED;

SELECT * FROM TOTAL_TEAM_CONCEDED;

/*SUMMARY TABLE*/
CREATE VIEW SUMMARY_TABLE
AS
SELECT 
TG.SEASON,
TG.TEAM,
TG.COUNTRY,
TG.LEAGUE,
TG.TOTAL_HOME_GOAL,
TOTAL_AWAY_GOAL,
TG.TOTAL_GOALS,
TC.TOTAL_HOME_CONCEDED,
TC.TOTAL_AWAY_CONCEDED,
TC.TOTAL_GOALS_CONCEDED 
FROM TOTAL_TEAM_GOALS TG
JOIN TOTAL_TEAM_CONCEDED TC
ON TG.TEAM = TC.TEAM
AND TG.SEASON = TC.SEASON
JOIN NOT_RELEGATED_TEAMS NRT
ON TG.TEAM = NRT.TEAM
GROUP BY TG.SEASON, 
TG.TEAM, 
TG.COUNTRY, 
TG.LEAGUE, 
TG.TOTAL_HOME_GOAL,
TOTAL_AWAY_GOAL,
TG.TOTAL_GOALS,
TC.TOTAL_HOME_CONCEDED,
TC.TOTAL_AWAY_CONCEDED,
TC.TOTAL_GOALS_CONCEDED 
ORDER BY TG.SEASON, TG.TEAM;

SELECT * FROM SUMMARY_TABLE;

/*TEAMS WITH THE MOST GOALS IN ENTIRE SEASON (THE MOST PRODUCTIVE TEAMS)*/
SELECT TEAM, SUM(TOTAL_GOALS) AS ALL_SEASON_GOALS
FROM SUMMARY_TABLE 
GROUP BY TEAM
ORDER BY SUM(TOTAL_GOALS) DESC;


/*TEAMS WITH THE MOST GOALS EACH SEASON*/
SELECT SEASON, TEAM, COUNTRY, LEAGUE, TOTAL_GOALS
FROM SUMMARY_TABLE 
ORDER BY TOTAL_GOALS DESC;

/*AVERAGE GOALS PRODUCED BY EACH TEAM EACH SEASON*/
SELECT 
TEAM,
COUNTRY,
LEAGUE,
ROUND(AVG(TOTAL_GOALS),1) AS AVERAGE_GOALS
FROM SUMMARY_TABLE
GROUP BY TEAM, COUNTRY, LEAGUE
ORDER BY AVERAGE_GOALS DESC;


/*TEAMS WITH THE MOST HOME GOALS EACH SEASON*/
SELECT 
SEASON,
TEAM,
COUNTRY,
LEAGUE,
TOTAL_HOME_GOAL
FROM SUMMARY_TABLE 
ORDER BY TOTAL_HOME_GOAL DESC;

/*TEAMS WITH THE MOST AWAY GOALS EACH SEASON*/
SELECT 
SEASON,
TEAM,
COUNTRY,
LEAGUE,
TOTAL_AWAY_GOAL
FROM SUMMARY_TABLE 
ORDER BY TOTAL_AWAY_GOAL DESC;

/*TEAMS WITH THE LEAST CONCEDED GOALS IN ENTIRE SEASON (TEAMS WITH BEST DEFEND)*/
SELECT 
TEAM,
COUNTRY,
LEAGUE,
SUM(TOTAL_GOALS_CONCEDED) AS ALL_SEASON_CONCEDED
FROM SUMMARY_TABLE
GROUP BY TEAM, COUNTRY, LEAGUE
ORDER BY ALL_SEASON_CONCEDED;

/*TEAMS WITH THE LEAST CONCEDED GOALS EACH SEASON*/
SELECT 
SEASON,
TEAM,
COUNTRY,
LEAGUE,
TOTAL_HOME_CONCEDED,
TOTAL_AWAY_CONCEDED, 
TOTAL_GOALS_CONCEDED
FROM SUMMARY_TABLE
ORDER BY TOTAL_GOALS_CONCEDED;

/*AVERAGE GOALS CONCEDED BY EACH TEAM*/
SELECT 
TEAM,
COUNTRY,
LEAGUE,
ROUND(AVG(TOTAL_GOALS_CONCEDED),1) AS AVERAGE_CONCEDED
FROM SUMMARY_TABLE
GROUP BY 
TEAM,
COUNTRY,
LEAGUE
ORDER BY AVERAGE_CONCEDED;

/*TEAMS WITH THE MOST GOAL DIFFERENCE EACH SEASON*/
SELECT 
SEASON,
TEAM,
COUNTRY,
LEAGUE,
TOTAL_GOALS-TOTAL_GOALS_CONCEDED AS GOAL_DIFF
FROM SUMMARY_TABLE
ORDER BY TOTAL_GOALS-TOTAL_GOALS_CONCEDED DESC;

/*FIND TOTAL WIN AND LOST BY EACH TEAM PER SEASON*/
CREATE VIEW TEAM_WIN_LOSE
AS 
WITH CTE AS
(SELECT 
M.SEASON,
T.TEAM_LONG_NAME AS TEAM,
C."NAME" AS COUNTRY,
L."NAME" AS LEAGUE,
CASE WHEN HOME_TEAM_GOAL > AWAY_TEAM_GOAL 
THEN 'WIN' ELSE 'LOSE' END AS RESULT
FROM "MATCH" M 
JOIN TEAM T 
ON M.HOME_TEAM_API_ID = T.TEAM_API_ID
JOIN COUNTRY C 
ON M.COUNTRY_ID = C.ID 
JOIN LEAGUE L 
ON M.LEAGUE_ID = L.ID 
UNION ALL
SELECT 
M.SEASON,
T.TEAM_LONG_NAME AS TEAM, 
C."NAME" AS COUNTRY,
L."NAME" AS LEAGUE,
CASE WHEN  AWAY_TEAM_GOAL > HOME_TEAM_GOAL
THEN 'WIN' ELSE 'LOSE' END AS RESULT
FROM "MATCH" M 
JOIN TEAM T 
ON M.AWAY_TEAM_API_ID  = T.TEAM_API_ID
JOIN COUNTRY C 
ON M.COUNTRY_ID = C.ID 
JOIN LEAGUE L 
ON M.LEAGUE_ID = L.ID)

SELECT
SEASON,
TEAM,
COUNTRY,
LEAGUE,
COUNT(*) AS TOTAL_MATCH,
SUM(CASE WHEN RESULT = 'WIN' THEN 1 ELSE 0 END) AS TOTAL_WIN,
SUM(CASE WHEN RESULT = 'LOSE' THEN 1 ELSE 0 END) AS TOTAL_LOSE
FROM CTE
WHERE TEAM IN (SELECT TEAM FROM NOT_RELEGATED_TEAMS NRT)
GROUP BY SEASON, TEAM, COUNTRY, LEAGUE
ORDER BY SEASON, TEAM;

SELECT * FROM TEAM_WIN_LOSE ;

/*FIND TOTAL WINS FROM EACH TEAM ALL SEASON*/
SELECT
TEAM,
COUNTRY,
LEAGUE,
SUM(TOTAL_WIN) AS TOTAL_WIN
FROM TEAM_WIN_LOSE
GROUP BY TEAM, COUNTRY, LEAGUE
ORDER BY TOTAL_WIN DESC; 

/*TEAM WITH THE FEWEST LOSSES IN ALL SEASONS*/
SELECT
TEAM,
COUNTRY,
LEAGUE,
SUM(TOTAL_LOSE) AS TOTAL_LOSE
FROM TEAM_WIN_LOSE
GROUP BY TEAM, COUNTRY, LEAGUE
ORDER BY TOTAL_LOSE; 

/*WINRATE FROM EACH TEAM*/
SELECT TEAM, 
ROUND(SUM(TOTAL_WIN)*100.0/SUM(TOTAL_MATCH),2) AS WINRATE,
ROUND(AVG(TOTAL_WIN),2) AS AVG_WIN,
floor(sum(total_match)/8) as total_match_per_season
FROM TEAM_WIN_LOSE TWL
GROUP BY TEAM
ORDER BY WINRATE DESC;

/*AVERAGE WIN PER SEASON*/
SELECT TEAM, 
ROUND(AVG(TOTAL_WIN),2) AS AVG_WIN,
floor(sum(total_match)/8) as total_match_per_season
FROM TEAM_WIN_LOSE TWL
GROUP BY TEAM
ORDER BY AVG_WIN DESC;

/*Top players by overall rating*/
SELECT 
player_name, ROUND(AVG(overall_rating),0) AS overall_rating
from Player p 
join Player_Attributes pa 
on p.player_api_id = pa.player_api_id
GROUP BY player_name 
ORDER BY overall_rating DESC;
